import type { Response } from "express";

export type ApiErrorCode =
  | "AUTH_REQUIRED"
  | "BOOK_ALREADY_EXISTS"
  | "BOOK_CREATE_FAILED"
  | "BOOK_DELETE_FAILED"
  | "BOOK_MANAGEMENT_FORBIDDEN"
  | "BOOK_NOT_FOUND"
  | "BOOK_SELECTION_INVALID"
  | "BOOK_VOTE_INVALID"
  | "BOOK_VOTE_NOMINATION_NOT_FOUND"
  | "BOOK_VOTE_ROUND_NOT_FOUND"
  | "BOOK_VOTE_ROUND_PERMISSION_DENIED"
  | "BOOK_VOTE_ROUND_STATE_INVALID"
  | "BOOK_UPDATE_FAILED"
  | "CLUB_NOT_FOUND"
  | "CLUB_MEMBER_REQUIRED"
  | "CLUB_MEMBERSHIP_REQUIRED"
  | "CLUB_OWNER_REQUIRED"
  | "CLUB_ACCESS_DENIED"
  | "DISCUSSION_ACCESS_DENIED"
  | "DISCUSSION_POST_INVALID"
  | "DISCUSSION_POST_NOT_FOUND"
  | "DISCUSSION_TOPIC_INVALID"
  | "DISCUSSION_TOPIC_LOCKED"
  | "DISCUSSION_TOPIC_NOT_FOUND"
  | "DISCUSSION_TOPIC_PERMISSION_DENIED"
  | "EMAIL_ALREADY_EXISTS"
  | "EXPIRED_TOKEN"
  | "FILE_TOO_LARGE"
  | "GOOGLE_BOOKS_BOOK_NOT_FOUND"
  | "GOOGLE_BOOKS_IMPORT_FAILED"
  | "GOOGLE_BOOKS_RATE_LIMITED"
  | "GOOGLE_BOOKS_SEARCH_FAILED"
  | "INVALID_FILE_TYPE"
  | "INVALID_CREDENTIALS"
  | "INVALID_TOKEN"
  | "JWT_SECRET_MISSING"
  | "PROFILE_LOAD_FAILED"
  | "PROFILE_UPDATE_FAILED"
  | "RATE_LIMITED"
  | "PLANNED_READING_CYCLE_EXISTS"
  | "INVALID_READING_CYCLE_DATES"
  | "READING_CYCLE_ALREADY_ACTIVE"
  | "READING_CYCLE_CREATE_FAILED"
  | "READING_CYCLE_INVALID_TRANSITION"
  | "READING_CYCLE_NOT_ACTIVE"
  | "READING_CYCLE_NOT_FOUND"
  | "READING_CYCLE_UPDATE_FAILED"
  | "READING_ENTRY_INVALID"
  | "READING_ENTRY_NOT_FOUND"
  | "READING_ENTRY_PERMISSION_DENIED"
  | "READING_PROGRESS_INVALID"
  | "READING_PROGRESS_NOT_ALLOWED"
  | "READING_PROGRESS_UPDATE_FAILED"
  | "READING_TARGET_CHANGE_NOT_ALLOWED"
  | "READING_TARGET_DATES_INVALID"
  | "READING_TARGET_INVALID"
  | "READING_TARGET_NOT_FOUND"
  | "READING_TARGET_ORDER_INVALID"
  | "READING_TARGET_OUTSIDE_CYCLE"
  | "READING_TARGET_OVERLAP"
  | "READING_TARGET_RANGE_INVALID"
  | "READING_TARGET_REORDER_FAILED"
  | "SESSION_RESTORE_FAILED"
  | "USERNAME_ALREADY_EXISTS"
  | "USER_NOT_FOUND"
  | "VALIDATION_ERROR";

export function sendError(
  res: Response,
  statusCode: number,
  code: ApiErrorCode,
  message: string,
) {
  return res.status(statusCode).json({
    status: "error",
    error: {
      code,
      message,
    },
  });
}
